package io.proj3ct.HabitTestingBot.dataType;

public enum ActivityState {
    USER_NAME_REQUIRED,PHONE_NUMBER_REQUIRED,EMAIL_REQUIRED,VERIFICATION_REQUIRED,LOGGED_IN, GROUP_NAME_REQUIRED,GROUP_MENU, ADD_USER_TO_GROUP, TEST_NAME_REQUIRED, TEST_MENU, QUESTION_REQUIRED,ANSWER_REQUIRED,TEST_PASSAGE
}
